package com.aiassistant.ml;

import android.util.Log;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

/**
 * AsyncLearningManager — asynchronous actor-learner architecture for on-device RL.
 *
 * Implements the A3C / IMPALA-style architecture adapted for Android:
 *
 *   ACTOR THREAD (main UI / accessibility thread):
 *     - Samples actions from current policy.
 *     - Accumulates experience into local rollout buffer.
 *     - Periodically publishes experience to shared queue.
 *
 *   LEARNER THREAD (background):
 *     - Dequeues experience batches.
 *     - Applies gradient updates to global network.
 *     - Pushes updated parameters back to actors.
 *
 *   V-TRACE (IMPALA correction):
 *     - Off-policy correction for trajectories generated by stale policies.
 *     - Importance sampling ratio clipping: ρ̄ = min(ρ̄_max, π/μ).
 *
 *   PRIORITISED EXPERIENCE SHARING:
 *     - Actor publishes only high-TD-error experiences (selective replay).
 *
 * Designed for single-process use on Android (simulated async via handler).
 * Thread-safe; actor and learner can run on separate threads.
 */
public class AsyncLearningManager {

    private static final String TAG = "AsyncLearner";

    // ─────────────────────────────────────────────────────────────────────────
    // Experience package sent from actor to learner
    // ─────────────────────────────────────────────────────────────────────────
    public static class RolloutBatch {
        public final float[][] states;
        public final int[]     actions;
        public final float[]   rewards;
        public final float[][] nextStates;
        public final boolean[] dones;
        public final float[]   logProbs;   // actor's log probabilities (for V-trace)
        public final int       actorId;
        public final int       batchSize;

        public RolloutBatch(int T, int stateDim, int actorId) {
            this.actorId   = actorId;
            this.batchSize = T;
            states      = new float[T][stateDim];
            actions     = new int[T];
            rewards     = new float[T];
            nextStates  = new float[T][stateDim];
            dones       = new boolean[T];
            logProbs    = new float[T];
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Fields
    // ─────────────────────────────────────────────────────────────────────────
    private final int      stateDim, actionDim, rolloutLen;
    private final float    gamma, vtraceLambda, rhoMax, cMax;
    private final boolean  useVTrace;

    // Shared experience queue (actor → learner)
    private final BlockingQueue<RolloutBatch> experienceQueue;
    private static final int QUEUE_CAPACITY = 64;

    // Global network (written by learner, read by actors)
    private volatile float[][] globalW1, globalW2, globalW3;
    private volatile float[]   globalB1, globalB2, globalB3;
    private final NeuralNetworkOptimizer globalOpt;
    private final Object networkLock = new Object();

    // Actor state (per-actor, simplified to single actor)
    private float[][] actorW1, actorW2, actorW3;
    private float[]   actorB1, actorB2, actorB3;
    private int       actorStep    = 0;
    private RolloutBatch currentRollout;
    private static final int ACTOR_ID = 0;

    // Stats
    private final AtomicInteger learnerUpdates = new AtomicInteger(0);
    private final AtomicInteger actorSteps     = new AtomicInteger(0);
    private final AtomicLong    totalBatches   = new AtomicLong(0);
    private final AtomicBoolean learnerActive  = new AtomicBoolean(false);
    private float avgLearnerLoss = 0f;
    private float avgActorReward = 0f;
    private int   queueSize      = 0;

    // ─────────────────────────────────────────────────────────────────────────
    // Construction
    // ─────────────────────────────────────────────────────────────────────────

    public AsyncLearningManager(int stateDim, int actionDim, int rolloutLen,
                                 int hidDim, float gamma, float vtraceLambda,
                                 float rhoMax, float cMax, boolean useVTrace,
                                 float lr) {
        this.stateDim     = stateDim;
        this.actionDim    = actionDim;
        this.rolloutLen   = rolloutLen;
        this.gamma        = gamma;
        this.vtraceLambda = vtraceLambda;
        this.rhoMax       = rhoMax;
        this.cMax         = cMax;
        this.useVTrace    = useVTrace;
        this.globalOpt    = new NeuralNetworkOptimizer(lr);
        this.experienceQueue = new LinkedBlockingQueue<>(QUEUE_CAPACITY);

        float s = (float)Math.sqrt(2.0/(stateDim+hidDim));
        globalW1 = xav(hidDim, stateDim, s); globalB1 = new float[hidDim];
        globalW2 = xav(hidDim, hidDim, s);   globalB2 = new float[hidDim];
        globalW3 = xav(actionDim+1, hidDim, s*0.01f); globalB3 = new float[actionDim+1];

        // Actor starts with copy of global
        syncActorToGlobal();
        currentRollout = new RolloutBatch(rolloutLen, stateDim, ACTOR_ID);

        Log.i(TAG, "AsyncLearningManager: s=" + stateDim + " a=" + actionDim
                + " rollout=" + rolloutLen + " vTrace=" + useVTrace);
    }

    public AsyncLearningManager(int stateDim, int actionDim) {
        this(stateDim, actionDim, 20, 128, 0.99f, 0.95f, 1.0f, 1.0f, true, 3e-4f);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Actor API (call from main/actor thread)
    // ─────────────────────────────────────────────────────────────────────────

    /** Actor: select action using local policy. */
    public int actorSelectAction(float[] state) {
        float[] s = pad(state, stateDim);
        float[] out = actorForward(s);
        float[] logits = new float[actionDim];
        System.arraycopy(out, 0, logits, 0, actionDim);
        float[] probs = softmax(logits);
        int a = sampleCat(probs);
        actorSteps.incrementAndGet();
        return a;
    }

    /** Actor: record step and publish batch when full. */
    public void actorStep(float[] state, int action, float reward,
                           float[] nextState, boolean done) {
        int t = actorStep % rolloutLen;
        float[] s = pad(state, stateDim);
        float[] sp = pad(nextState, stateDim);

        currentRollout.states[t]     = s;
        currentRollout.actions[t]    = action;
        currentRollout.rewards[t]    = reward;
        currentRollout.nextStates[t] = sp;
        currentRollout.dones[t]      = done;

        float[] out = actorForward(s);
        float[] logits = new float[actionDim];
        System.arraycopy(out, 0, logits, 0, actionDim);
        float[] probs = softmax(logits);
        currentRollout.logProbs[t] = (float)Math.log(Math.max(probs[Math.min(action,actionDim-1)], 1e-8f));

        avgActorReward = 0.99f*avgActorReward + 0.01f*reward;
        actorStep++;

        if (actorStep % rolloutLen == 0 || done) {
            publishBatch();
        }
    }

    private void publishBatch() {
        RolloutBatch batch = currentRollout;
        currentRollout = new RolloutBatch(rolloutLen, stateDim, ACTOR_ID);
        actorStep = 0;
        if (!experienceQueue.offer(batch)) {
            Log.w(TAG, "Experience queue full — dropping batch");
        } else {
            totalBatches.incrementAndGet();
        }
        // Sync actor weights from global
        syncActorToGlobal();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Learner API (call from background learner thread or periodically)
    // ─────────────────────────────────────────────────────────────────────────

    /** Learner: process one batch from the queue. Returns false if queue empty. */
    public boolean learnerStep() {
        RolloutBatch batch = experienceQueue.poll();
        if (batch == null) return false;

        queueSize = experienceQueue.size();
        float loss = processBatch(batch);
        avgLearnerLoss = 0.99f*avgLearnerLoss + 0.01f*loss;
        learnerUpdates.incrementAndGet();
        return true;
    }

    private float processBatch(RolloutBatch b) {
        float totalLoss = 0;
        for (int t=0;t<b.batchSize;t++) {
            float[] s  = b.states[t];
            float[] sp = b.nextStates[t];
            int     a  = Math.min(b.actions[t], actionDim-1);
            float   r  = b.rewards[t];
            boolean d  = b.dones[t];

            // Global network forward
            float[] outS  = globalForward(s);
            float[] outSp = globalForward(sp);
            float[] logitsS = new float[actionDim]; System.arraycopy(outS,0,logitsS,0,actionDim);
            float   VS  = outS[actionDim];
            float   VSp = outSp[actionDim];

            float[] probsS = softmax(logitsS);
            float curLogP  = (float)Math.log(Math.max(probsS[a], 1e-8f));

            // V-trace importance ratio
            float rho = useVTrace ? Math.min(rhoMax, (float)Math.exp(curLogP - b.logProbs[t])) : 1f;
            float c   = useVTrace ? Math.min(cMax,   (float)Math.exp(curLogP - b.logProbs[t])) : 1f;

            float delta  = rho * (r + (d?0f:gamma*VSp) - VS);
            float vTarget= VS + delta;

            // Policy gradient: actor loss
            float adv = delta;
            float[] dLogits = probsS.clone(); dLogits[a] -= 1f;
            for(int i=0;i<actionDim;i++) dLogits[i] *= -rho * adv;
            // Critic loss
            float vErr = VS - vTarget;
            // Combined gradient
            float[] dOut = new float[actionDim+1];
            System.arraycopy(dLogits, 0, dOut, 0, actionDim);
            dOut[actionDim] = 2f * vErr;

            globalBackprop(s, dOut);
            totalLoss += vErr*vErr;
        }
        return totalLoss / b.batchSize;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Network forward / backward
    // ─────────────────────────────────────────────────────────────────────────

    private float[] actorForward(float[] s) {
        return linF(actorW3, actorB3, linRelu(actorW2, actorB2, linRelu(actorW1, actorB1, s)));
    }

    private float[] globalForward(float[] s) {
        synchronized (networkLock) {
            return linF(globalW3, globalB3, linRelu(globalW2, globalB2, linRelu(globalW1, globalB1, s)));
        }
    }

    private void globalBackprop(float[] s, float[] dOut) {
        synchronized (networkLock) {
            float[] h1 = linRelu(globalW1, globalB1, s);
            float[] h2 = linRelu(globalW2, globalB2, h1);
            float[][] dW3 = outer(dOut, h2);
            globalOpt.step("al_W3", globalW3, dW3);
            float[] dH2 = new float[globalW2.length];
            for(int j=0;j<dH2.length;j++){if(h2[j]<=0)continue;for(int i=0;i<dOut.length;i++)dH2[j]+=dOut[i]*globalW3[i][j];}
            globalOpt.step("al_W2", globalW2, outer(dH2, h1));
            float[] dH1=new float[globalW1.length];
            for(int j=0;j<dH1.length;j++){if(h1[j]<=0)continue;for(int i=0;i<dH2.length;i++)dH1[j]+=dH2[i]*globalW2[i][j];}
            globalOpt.step("al_W1", globalW1, outer(dH1, s));
        }
    }

    private void syncActorToGlobal() {
        synchronized (networkLock) {
            actorW1=clone2d(globalW1); actorW2=clone2d(globalW2); actorW3=clone2d(globalW3);
            actorB1=globalB1.clone(); actorB2=globalB2.clone(); actorB3=globalB3.clone();
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private static float[] linRelu(float[][] W, float[] b, float[] x) {
        float[] o=new float[W.length];for(int i=0;i<W.length;i++){float s=b[i];for(int j=0;j<Math.min(x.length,W[i].length);j++)s+=W[i][j]*x[j];o[i]=Math.max(0f,s);}return o;
    }
    private static float[] linF(float[][] W, float[] b, float[] x) {
        float[] o=new float[W.length];for(int i=0;i<W.length;i++){float s=b[i];for(int j=0;j<Math.min(x.length,W[i].length);j++)s+=W[i][j]*x[j];o[i]=s;}return o;
    }
    private static float[] softmax(float[] v){float mx=v[0];for(float x:v)if(x>mx)mx=x;float sum=0;float[] o=new float[v.length];for(int i=0;i<v.length;i++){o[i]=(float)Math.exp(v[i]-mx);sum+=o[i];}for(int i=0;i<v.length;i++)o[i]/=sum;return o;}
    private int sampleCat(float[] p){float r=(float)Math.random(),c=0;for(int a=0;a<p.length-1;a++){c+=p[a];if(r<c)return a;}return p.length-1;}
    private static float[][] outer(float[] a, float[] b){float[][] g=new float[a.length][b.length];for(int i=0;i<a.length;i++) for(int j=0;j<b.length;j++) g[i][j]=a[i]*b[j];return g;}
    private static float[] pad(float[] x,int dim){if(x.length==dim)return x;float[] p=new float[dim];System.arraycopy(x,0,p,0,Math.min(x.length,dim));return p;}
    private static float[][] clone2d(float[][] m){float[][] c=new float[m.length][];for(int i=0;i<m.length;i++)c[i]=m[i].clone();return c;}
    private float[][] xav(int r,int c,float s){float[][] m=new float[r][c];for(int i=0;i<r;i++) for(int j=0;j<c;j++) m[i][j]=((float)Math.random()*2f-1f)*s;return m;}

    // ─────────────────────────────────────────────────────────────────────────
    // Stats
    // ─────────────────────────────────────────────────────────────────────────

    public Map<String, Object> getStats() {
        Map<String, Object> s = new HashMap<>();
        s.put("learnerUpdates", learnerUpdates.get());
        s.put("actorSteps",     actorSteps.get());
        s.put("totalBatches",   totalBatches.get());
        s.put("queueSize",      queueSize);
        s.put("avgLearnerLoss", avgLearnerLoss);
        s.put("avgActorReward", avgActorReward);
        s.put("useVTrace",      useVTrace);
        return s;
    }
}
